name: Production

on:
  workflow_run:
    workflows:
      - staging
    types:
      - completed

jobs:
  succeed:
    name: Always Succeed
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name ==
      'workflow_dispatch'
    steps:
      - name: Ensure Success
        run: echo "This workflow always succeeds!"
