name: Staging

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 30

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 2
        run: sleep 30

  job3:
    name: Job 3 (Always Fail)
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Step 3
        run: |
          sleep 30
          exit 1
